### ISSUE TITLE
Znajdywanie najbliższego wierzchołka

### ISSUE THREAD

**Issue by MarcinG121** [MarcinG121/INPGProject#1]
Aby znaleźć najbliższy wierzchołek iteruje po całym grafie co jest dość nieoptymalnym rozwiązaniem gdyby miał ktoś lepszy pomysł jak wyszukiwać tego wierzchołka byłbym wdzięczny za pomoc :)

**Comment by sebgol12** [comment]
Można by przeszukiwać graf jakąś metodą na przykład:
https://pl.wikipedia.org/wiki/Przeszukiwanie_wszerz
I wtedy jak przez ileś wierzchołków się oddalamy to dalej nie iść.

**Comment by MarcinG121** [comment]
Dzięki wielkie za pomoc zabieram się do pracy nad tym
